login_check:
  path:     /api/login_check
  methods:  [POST]

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#user_create:
 # path: api/customers
 # controller: App\Controller\CustomerController:createAction
 # methods: [POST]